---

- name: zshrc
  get_url:
    url: https://raw.githubusercontent.com/elisboa/rcfiles/master/.zshrc
    dest: "~/.zshrc"
    backup: yes
    force: yes
    mode: '0664'
  tags: configurar:base:zsh

- name: vimrc
  get_url:
    url: https://raw.githubusercontent.com/elisboa/rcfiles/master/.vimrc
    dest: "~/.vimrc"
    backup: yes
    force: yes
    mode: '0664'
  tags: configurar:base:vimrc

- name: tmux conf
  get_url:
    url: https://raw.githubusercontent.com/elisboa/rcfiles/master/.tmux.conf
    dest: "~/.tmux.conf"
    backup: yes
    force: yes
    mode: '0664'
  tags: configurar:base:zsh


- name: ssh user config
  get_url:
    url: https://raw.githubusercontent.com/elisboa/rcfiles/master/ssh/config
    dest: "~/.ssh/config"
    backup: yes
    force: yes
    mode: '0600'
  tags: configurar:base:ssh
