---
# Variáveis "packages_*": listas de configurar independentes e/ou que são dependências de
# várias aplicações simultaneamente. Vários provavelmente já estarão instalados,
# mas não custa documentá-los.

# Nota: os configurar são instalados com *no-install-recommends*!

configurar_base:

configurar_util:

configurar_fancy:

configurar_dev:

configurar_devops:
