---
- name: Workstation - Base System
  hosts: all

  roles:
    - role: pacotes
      tags: pacotes
      
#    - role: packages
#      tags: packages
#    - role: base-system
#      tags: base-system
#    - role: dotfiles
#      tags: dotfiles
#    - role: desktop
#      tags: desktop
