---
#- name: Atualiza cache do APT
#  apt:
#    update_cache: true
#    cache_valid_time: 3600
#  tags: packages:apt-update

- name: Instala pacotes básicos
  pacman:
    name: "{{ pacotes_base }}"
    state: latest
    update_cache: yes # sempre atualizar o cache
  tags: pacotes:base

- name: Instala pacotes úteis
  pacman:
    name: "{{ pacotes_util }}"
    state: latest
    update_cache: yes # sempre atualizar o cache
  tags: pacotes:util

- name: Instala pacotes fancy
  pacman:
    name: "{{ pacotes_fancy }}"
    state: latest
    update_cache: yes # sempre atualizar o cache
  tags: pacotes:fancy

- name: Instala pacotes manualmente fancy
  command: gem install colorls
  command: yay -S --noconfirm nerd-fonts-fantasque-sans-mono
  tags: pacotes:fancy

- name: Instala pacotes dev
  pacman:
    name: "{{ pacotes_dev }}"
    state: latest
    update_cache: yes # sempre atualizar o cache
  tags: pacotes:dev

#- name: Instala gemas fancy
#  gem:
#    name: "{{ gemas_fancy }}"
#    state: present
#    repository: http://rubygems.org
#  tags: gemas:fancy

#- name: Instala ferramentas de desenvolvimento
#  apt:
#    name: "{{ packages_dev }}"
#    state: present
#    install_recommends: false
#  tags: packages:dev
#
#- name: Instala ferramentas de administração de sistema
#  apt:
#    name: "{{ packages_sysadmin }}"
#    state: present
#    install_recommends: false
#  tags: packages:sysadmin
#
#- name: Instala ferramentas de gráficos e multimídia
#  apt:
#    name: "{{ packages_media }}"
#    state: present
#    install_recommends: false
#  tags: packages:media
#
#- name: Instala pacotes utilitários
#  apt:
#    name: "{{ packages_utils }}"
#    state: present
#    install_recommends: false
#  tags: packages:utils
#
#- name: Remove pacotes selecionados
#  apt:
#    name: "{{ packages_purge }}"
#    state: absent
#    purge: true
#  tags: packages:purge
#
#- name: Instala pacotes extras
#  apt:
#    name: "{{ packages_extra }}"
#    state: present
#    install_recommends: false
#  tags: packages:extra
#
## Git (instalado à parte por usar PPA)
#
#- name: Habilita PPA do Git
#  apt_repository:
#    repo: ppa:git-core/ppa
#    state: present
#    update_cache: true
#  tags:
#    - packages:git
#    - packages:git:ppa
#    - packages:dev
#
#- name: Instala pacotes relacionados ao Git
#  apt:
#    name:
#      - git
#      - git-doc
#      - git-gui
#      - gitk
#      - qgit
#      - tig
#    state: present
#    install_recommends: false
#  tags:
#    - packages:git
#    - packages:dev
#
#- name: Configura alternatives
#  alternatives:
#    name: editor
#    path: /usr/bin/vim.basic
#  tags: packages:alternatives
#